version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo Checking project structure...
      - ls -R

  build:
    commands:
      - echo Building project...
      - npm install
      - npm run build
      

artifacts:
  files:
    - '**/*'
  base-directory: dist-server
  name: compiled.zip

